### ISSUE TITLE
Record User-Agent

### ISSUE THREAD

**Issue by satoved** [sarfraznawaz2005/larafeed#1]
Sometimes user's issue is related to browser version or OS.

I think it'll be nice to record the User-Agent of the browser along with IP, screenshot and URL.

I can make a PR if it's welcome.

**Comment by sarfraznawaz2005** [comment]
Sounds good, I will add this and probably allow custom fields in future. thx

**Comment by sarfraznawaz2005** [comment]
Added `browser` and `os` info in version 2.0.0. thx
